services:
  metadata-service:
    restart: always
    image: nginx:latest
    container_name: metadata-service.mediamaster.internal
    hostname: metadata-service.mediamaster.internal
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8100:8100"
    networks:
      - mediamaster-internal-network

networks:
  mediamaster-internal-network:
    name: mediamaster-internal-network
